apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-2-service
  namespace: nginx-demo-2
  labels:
    app: nginx-demo-2
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: nginx-demo-2
